=== OSDeploy/osdws-winpedriver-dell/winpe-driver/arm64/Dell-XPS13-9345/driverarchivemanifest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:attribute name="BiosID" type="xs:string"/>

  <!-- Group of attributes that describe an OS -->
  <xs:attributeGroup name="AG_OS">
    <xs:attribute name="Name" type="OS_Display_Names" use="required" />
    <xs:attribute name="Arch" type="Architecture_Display_Names" use="optional" />
    <xs:attribute name="ID" use="optional" />
    <xs:attribute name="MajorVersion" type="xs:unsignedInt" use="required" />
    <xs:attribute name="MinorVersion" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="BuildNumber" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="ServicePackMajor" type="xs:unsignedShort" use="optional" />
    <xs:attribute name="ServicePackMinor" type="xs:unsignedShort" use="optional" />
    <xs:attribute name="Type" type="OS_Types" use="optional" />
  </xs:attributeGroup>
  <xs:simpleType name="OS_Display_Names">
    <xs:restriction  base="xs:string">
      <xs:enumeration value="WinXP"/>
      <xs:enumeration value="Vista"/>
      <xs:enumeration value="Windows7"/>
      <xs:enumeration value="Windows8"/>
      <xs:enumeration value="Windows8.1"/>
      <xs:enumeration value="Windows10"/>
      <xs:enumeration value="Win2K3"/>
      <xs:enumeration value="Win2K8"/>
      <xs:enumeration value="winpe"/>
	  <xs:enumeration value="Windows11"/>	  
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="OS_Types">
    <xs:restriction  base="xs:string">
      <xs:enumeration value="xp"/>
      <xs:enumeration value="vista"/>
      <xs:enumeration value="win7"/>
      <xs:enumeration value="win8"/>
      <xs:enumeration value="win8.1"/>
      <xs:enumeration value="win10"/>
      <xs:enumeration value="winpe"/>
	  <xs:enumeration value="win11"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Architecture_Display_Names">
    <xs:restriction base="xs:string">
      <xs:enumeration value="x86"/>
      <xs:enumeration value="x64"/>
	  <xs:enumeration value="arm64"/>
      <xs:enumeration value="IA64"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- define elements -->
  <xs:complexType name="T_Package">
    <!-- In some uses the destination path identifies where the file needs to be copied to be used. -->
    <xs:attribute name="DestPath" type="xs:string" use="optional"/>
    <!-- identifies the location relative to the catalog.xml where the files of the release exist -->
    <xs:attribute name="SrcPath" type="xs:string"  use="required"/>
  </xs:complexType>

  <xs:complexType name="T_Release" mixed="true">
    <xs:sequence>
      <!-- Why is maxOccurs not 1?  Are we expecting the same release to show up in multiple directories? -->
      <xs:element name="Package" type="T_Package" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="ReleaseID" type="xs:string" use="required" />
    <!-- ReleaseType corresponds to the i-drive releasetype assigned. -->
    <xs:attribute name="ReleaseType" type="xs:string" use="required"/>
    <!-- Dell version assigned to release -->
    <xs:attribute name="DellVersion" type="xs:string" use="required"/>
    <xs:attribute name="VendorVersion" type="xs:string" use="required" />
    <xs:attribute name="Category" type="xs:string" use="required"/>
    <!--Commented as requested to Hide The vendor name in HTML File, Till Agile Data is matured -->
    <!--<xs:attribute name="VendorName" type="xs:string" use="optional" />-->
    <xs:attribute name="DeviceDescription" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="T_OS" mixed="true">
    <xs:sequence>
      <xs:element name="Release" type="T_Release" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="AG_OS"/>
  </xs:complexType>

  <xs:complexType name="Type_System" mixed="true">
    <xs:sequence>
      <xs:element name="OS" type="T_OS" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="AG_System"/>
  </xs:complexType>

  <xs:attributeGroup name="AG_System">
    <xs:attribute name="LOB" type="xs:string" use="optional" />
    <xs:attribute name="Brand" type="xs:string" use="optional"/>
    <xs:attribute name="Model" type="xs:string" use="optional"/>
    <xs:attribute name="SDLRBlock" type="xs:string" use="optional"/>
    <xs:attribute name="SDLRVersion" type="xs:string" use="optional"/>
    <xs:attribute name="SystemID" type="xs:string" use="optional" />
  </xs:attributeGroup>

  <!-- Are we planning to use the exact same catalog for both maser and driver archives? or was this really supposed to be
    a set of common types -->
  <xs:element name="Catalog" type="Type_Catalog"/>
  <xs:complexType name="Type_Catalog" mixed="true">
    <xs:sequence>
      <xs:element name="System" type="Type_System" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="CreateDate" type="xs:dateTime" use="required" />
    <xs:attribute name="ReleaseID" type="xs:string" use="optional" />
    <xs:attribute name="Version" type="xs:string" use="optional" />
    <xs:attribute name="Application" type="xs:string" use="optional"/>
    <!-- is this the version of the application that generated the catalog -->
    <xs:attribute name="ApplicationVersion" type="xs:string" use="optional"/>
  </xs:complexType>
</xs:schema>

=== OSDeploy/osdws-winpedriver-dell/winpe-driver/arm64/Dell-XPS13-9345/Manifest.xml
<?xml version="1.0"?>
<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="driverarchivemanifest.xsd" CreateDate="2024-06-14T08:28:35.6299977Z" Version="A00" ReleaseID="PVCKV_X03-00" Application="ManiFestFile From CAB" ApplicationVersion="1.0">
  <System SystemID="0C69" LOB="XPS Notebook" Model="XPS-13-9345">
    <OS Name="Windows11" Arch="arm64" MajorVersion="10" MinorVersion="0" Type="win11">
      <Release ReleaseID="CTKXD_A00-00" ReleaseType="Driver" Category="security" DeviceDescription="Goodix Fingerprint Sensor Driver" DellVersion="A00" VendorVersion="4.10.5.330">
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocEngineAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocEngineAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocEngineAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocEngineAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocSensorAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocSensorAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocSensorAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocSensorAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocStorageAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocStorageAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocStorageAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocStorageAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocUsb.cat" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocUsb.cat" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocUsb.inf" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocUsb.inf" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocWbdi.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixMocWbdi.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixSessionService.exe" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID631C\GoodixSessionService.exe" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocEngineAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocEngineAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocEngineAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocEngineAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocSensorAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocSensorAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocSensorAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocSensorAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocStorageAdapter.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocStorageAdapter.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocStorageAdapterNw.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocStorageAdapterNw.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocUsb.cat" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocUsb.cat" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocUsb.inf" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocUsb.inf" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocWbdi.dll" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixMocWbdi.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixSessionService.exe" SrcPath="XPS-13-9345\Win11\arm64\security\CTKXD_A00-00\22621\Drivers\Goodix_PID633C\GoodixSessionService.exe" />
      </Release>
      <Release ReleaseID="NPCT8_A00-00" ReleaseType="Driver" Category="audio" DeviceDescription="Qualcomm Audio Driver" DellVersion="A02" VendorVersion="1.0.4019.5861">
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\BIOSIntf.dll" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\BIOSIntf.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\dellgmuteext.cat" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\dellgmuteext.cat" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteExt.inf" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteExt.inf" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSupp.dll" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSupp.dll" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSvc.exe" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSvc.exe" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSvc.exe.config" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSvc.exe.config" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\dellgmutesw.cat" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\dellgmutesw.cat" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSw.inf" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\Gmute\DellGMuteSw.inf" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\acdb_cal_FG.acdb" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\acdb_cal_FG.acdb" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\acdb_cal_Veco.acdb" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\acdb_cal_Veco.acdb" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\ADCMResources.bin" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\ADCMResources.bin" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__2.9.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__2.9.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__3.0.0_0.0__eai_2.10_enpuv3.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__3.0.0_0.0__eai_2.10_enpuv3.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__4.8.5_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\fai__4.8.5_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_2.25.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\ffv__5.0.1_0.1__eai_2.21_enpu3.pmd" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\ffv__5.0.1_0.1__eai_2.21_enpu3.pmd" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\qcacsp8380.cat" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\qcacsp8380.cat" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\qcacsp_crd8380.inf" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\qcacsp_crd8380.inf" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\workspaceFile_FG.qwsp" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\workspaceFile_FG.qwsp" />
        <Package DestPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\workspaceFile_Veco.qwsp" SrcPath="XPS-13-9345\Win11\arm64\audio\NPCT8_A00-00\qcacsp_crd8380\workspaceFile_Veco.qwsp" />
